In [1]:
# Install libraries if needed
import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Uncomment if not installed
# install('pandas')
# install('numpy')
# install('scikit-learn')
# install('xgboost')
# install('matplotlib')
# install('seaborn')

print("✅ All libraries ready!")

✅ All libraries ready!

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported!")

✅ Libraries imported!

In [3]:
# Load the dataset
# Make sure the CSV file is in your data folder

df = pd.read_csv('../data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

print("✅ Data loaded successfully!")
print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")

✅ Data loaded successfully!
Shape: 7043 rows × 21 columns

In [4]:
# View first 5 rows
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
# View last 5 rows
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [6]:
# Check data types and info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
# Check missing values
print("Missing Values:")
print("=" * 40)
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
})

print(missing_df[missing_df['Missing Count'] > 0])
print("\n✅ Missing value check complete!")

Missing Values:
========================================
Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

✅ Missing value check complete!

In [8]:
# Check unique values for each column
print("Unique Values Per Column:")
print("=" * 40)
for col in df.columns:
    print(f"{col:<25} : {df[col].nunique()} unique values")

Unique Values Per Column:
========================================
customerID                : 7043 unique values
gender                    : 2 unique values
SeniorCitizen             : 2 unique values
Partner                   : 2 unique values
Dependents                : 2 unique values
tenure                    : 73 unique values
PhoneService              : 2 unique values
MultipleLines             : 3 unique values
InternetService           : 3 unique values
OnlineSecurity            : 3 unique values
OnlineBackup              : 3 unique values
DeviceProtection          : 3 unique values
TechSupport               : 3 unique values
StreamingTV               : 3 unique values
StreamingMovies           : 3 unique values
Contract                  : 3 unique values
PaperlessBilling          : 2 unique values
PaymentMethod             : 4 unique values
MonthlyCharges            : 1585 unique values
TotalCharges              : 6531 unique values
Churn                     : 2 unique values

In [9]:
# Check target variable distribution
print("Target Variable: Churn")
print("=" * 40)
churn_counts = df['Churn'].value_counts()
churn_pct = df['Churn'].value_counts(normalize=True) * 100

for val in churn_counts.index:
    print(f"  {val}: {churn_counts[val]} customers ({churn_pct[val]:.1f}%)")

print(f"\n⚠️  Class Imbalance: {churn_pct['No']:.1f}% stayed vs {churn_pct['Yes']:.1f}% churned")

Target Variable: Churn
========================================
  No: 5174 customers (73.5%)
  Yes: 1869 customers (26.5%)

⚠️  Class Imbalance: 73.5% stayed vs 26.5% churned

In [10]:
# DATA CLEANING

# Step 1: Drop customerID (not useful)
df = df.drop('customerID', axis=1)
print("✅ Dropped customerID column")

# Step 2: Fix TotalCharges (it has spaces, should be numeric)
print(f"\nTotalCharges dtype before: {df['TotalCharges'].dtype}")
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(f"TotalCharges dtype after : {df['TotalCharges'].dtype}")

# Step 3: Check how many NaN created
nan_count = df['TotalCharges'].isnull().sum()
print(f"NaN values created: {nan_count}")

# Step 4: Fill NaN with median
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)
print(f"✅ Filled {nan_count} NaN values with median")

print("\n✅ Data cleaning complete!")

✅ Dropped customerID column

TotalCharges dtype before: object
TotalCharges dtype after : float64
NaN values created: 11
✅ Filled 11 NaN values with median

✅ Data cleaning complete!

In [11]:
# ENCODE CATEGORICAL VARIABLES
from sklearn.preprocessing import LabelEncoder

# Make a copy for encoding
df_encoded = df.copy()

# Get all categorical columns
categorical_cols = df_encoded.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns to encode:")
print(categorical_cols)

# Remove target from list
if 'Churn' in categorical_cols:
    categorical_cols.remove('Churn')

# Encode each column
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    label_encoders[col] = le
    print(f"  ✅ Encoded: {col}")

# Encode target variable
df_encoded['Churn'] = df_encoded['Churn'].map({'Yes': 1, 'No': 0})
print("  ✅ Encoded: Churn (Yes=1, No=0)")

print("\n✅ Encoding complete!")

Categorical columns to encode:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
  ✅ Encoded: gender
  ✅ Encoded: Partner
  ✅ Encoded: Dependents
  ✅ Encoded: PhoneService
  ✅ Encoded: MultipleLines
  ✅ Encoded: InternetService
  ✅ Encoded: OnlineSecurity
  ✅ Encoded: OnlineBackup
  ✅ Encoded: DeviceProtection
  ✅ Encoded: TechSupport
  ✅ Encoded: StreamingTV
  ✅ Encoded: StreamingMovies
  ✅ Encoded: Contract
  ✅ Encoded: PaperlessBilling
  ✅ Encoded: PaymentMethod
  ✅ Encoded: Churn (Yes=1, No=0)

✅ Encoding complete!

In [12]:
# View encoded dataframe
print("Encoded DataFrame:")
df_encoded.head()

Encoded DataFrame:

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

In [13]:
# Save cleaned data
df_encoded.to_csv('../data/cleaned_data.csv', index=False)
print("✅ Cleaned data saved to ../data/cleaned_data.csv")
print(f"Shape: {df_encoded.shape}")

✅ Cleaned data saved to ../data/cleaned_data.csv
Shape: (7043, 20)

In [14]:
# Summary
print("=" * 50)
print("📋 DATA PREPARATION SUMMARY")
print("=" * 50)
print(f"Total Customers  : {len(df_encoded)}")
print(f"Total Features   : {df_encoded.shape[1] - 1}")
print(f"Target Variable  : Churn")
print(f"Churned (1)      : {df_encoded['Churn'].sum()}")
print(f"Stayed  (0)      : {(df_encoded['Churn'] == 0).sum()}")
print(f"Churn Rate       : {df_encoded['Churn'].mean()*100:.1f}%")
print("\n✅ Notebook 1 Complete! Move to Notebook 2: EDA")

==================================================
📋 DATA PREPARATION SUMMARY
==================================================
Total Customers  : 7043
Total Features   : 19
Target Variable  : Churn
Churned (1)      : 1869
Stayed  (0)      : 5174
Churn Rate       : 26.5%

✅ Notebook 1 Complete! Move to Notebook 2: EDA